name: np_com_pandeykushal
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State_management
  provider: ^6.1.1
  get: ^4.6.6
  go_router: ^14.1.2

  # NETWORK_CALLS
  flutter_local_notifications: ^17.1.2
  flutter_html: ^3.0.0-beta.2
  dio: ^5.3.4

  # LOCAL STORAGE
  flutter_secure_storage: ^9.0.0

  # FILES
  

  # FIREBASE
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  firebase_auth: ^4.7.2

  # IMAGES
  cached_network_image: ^3.3.0

  #font
  google_fonts: ^6.2.1

  # UI
  flutter_screenutil: ^5.9.0
  bot_toast: ^4.1.3
  responsive_framework: ^1.1.1
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  flutter_statusbarcolor_ns: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/icon/

 
#Basic template  for the Flutter app Created By :kushalpandey.com.np
#Flutter  :Kushal Pandey ;
